version: "1"
services:
- type: web
  name: todo
  runtime: node
  plan: free
  region: oregon
  repo: https://github.com/jobscale/todo-app
  branch: main
  buildCommand: npm i && npm i --no-save serve && npm run build
  startCommand: npm start
  autoDeploy: true
  envVars:
  - key: ENV
    sync: false
  domains:
  - todo.jsx.jp
